# Generated by Django 4.0.4 on 2022-04-23 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_adress_zip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='feature_product',
            new_name='featured_product',
        ),
    ]
