# Generated by Django 4.0.4 on 2022-04-23 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_feature_product_collection_featured_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unit_price',
        ),
    ]
