# Generated by Django 4.1 on 2022-08-15 06:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_orderitem_product_alter_product_collection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
