# Generated by Django 4.1 on 2022-08-27 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('cancel_order', 'Can Cancel Order')]},
        ),
    ]
