# Generated by Django 4.1 on 2022-08-27 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_customer_membership'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['user__last_name', 'user__first_name'], 'permissions': [('view_history', 'Can View History')]},
        ),
    ]
